### ISSUE TITLE
import Parse

### ISSUE THREAD

**Issue by aalzanki** [MakeSchool-Tutorials/Makestagram-Swift#13]
Even though we imported Parse here: https://github.com/MakeSchool-Tutorials/Makestagram-Swift/blob/master/P5-Connecting-to-Parse/content.md

My TimelineViewController doesn't recognize it here: https://github.com/MakeSchool-Tutorials/Makestagram-Swift/blob/master/P8-Uploading-Photos-Parse/content.md

Not sure if this is specific to me. Everything works fine when I import it again in TimelineViewController.

**Comment by adamreis** [comment]
@samaratrilling and I ran into this too

**Comment by Ben-G** [comment]
The `import` statement needs to be present in every individual file. Thanks for catching!
