### ISSUE TITLE
Tricky building starter project on first download

### ISSUE THREAD

**Issue by afbrandt** [MakeSchool-Tutorials/Makestagram-Swift#2]
Ran into a problem initially building the project.  The project doesn't open to the correct scheme right away, and my initial confusion trying to fix the error may have inadvertently exacerbated it.  Trying to work out steps to duplicate.

**Comment by Ben-G** [comment]
Thanks @afbrandt  for pointing this out! The scheme of the main app was not shared. Fixed now.
Also made some additional changes to starter project. I can show you how to perform the changes to your existing project so that you don't need to start over.
