### ISSUE TITLE
P18 on Makestagram doesn't have a 'move on' button to P19

### ISSUE THREAD

**Issue by samaratrilling** [MakeSchool-Tutorials/Makestagram-Swift#25]
The last page of Makestagram says 'in the last section we'll look back on what we learned' but there's not a forward arrow button at the bottom to access P19.

**Comment by Ben-G** [comment]
This seems to be an off by one issue in the Online Academy, will talk to Gerald. Thanks!

**Comment by Ben-G** [comment]
This has been fixed.
