### ISSUE TITLE
Parse is A/B testing?

### ISSUE THREAD

**Issue by afbrandt** [MakeSchool-Tutorials/Makestagram-Swift#3]
When interacting with Parse for the first time, I had a slightly different flow when creating an account.  Two things are different:
-The signup form is a little different:
![screen shot 2015-06-03 at 1 30 23 pm](https://cloud.githubusercontent.com/assets/1735651/7970723/ce930446-09f4-11e5-81c6-092a386ce109.png)
-My first project did not create a user model by default

**Comment by samaratrilling** [comment]
Word - Parse no longer creates a user class automatically, so there should be an extra step added before creating the Post class. All students have to do is create a new class of type User instead of Custom, and Parse fills in the rest.
