### ISSUE TITLE
Parse 

### ISSUE THREAD

**Issue by rahb3rt** [MakeSchool-Tutorials/Makestagram-Swift#41]
Parse is now run through GitHub so you have to install mongodb the backend of parse along with Parse Dashboard.

**Comment by danielhaaser** [comment]
@rahb3rt please see the updated tutorial [here!](https://github.com/MakeSchool-Tutorials/Makestagram-Swift-V2)

**Comment by rahb3rt** [comment]
Awesome @djh- thank you!
