### ISSUE TITLE
post.image == nil problem

### ISSUE THREAD

**Issue by rahb3rt** [MakeSchool-Tutorials/Makestagram-Swift#42]
``` swift
func downloadImage() {
  // if image is not downloaded yet, get it
  // 1
  if (image.value == nil) {
    // 2
    imageFile?.getDataInBackgroundWithBlock { (data: NSData?, error: NSError?) -> Void in
      if let data = data {
        let image = UIImage(data: data, scale:1.0)!
        // 3
        self.image.value = image
      }
    }
  }
}
```

image.value says its deprecated because obviously image does not exist. But do we want to call post!.image.value instead here?

If we do run post.image.value though we get a memory error..

Any ideas?

**Comment by danielhaaser** [comment]
@rahb3rt You should have a property in your `Post` class that looks like this:

``` swift
    var image: Observable<UIImage?> = Observable(nil)
```

With that property, the assignment `self.image.value = image` should work.

**Comment by danielhaaser** [comment]
Also, btw you opened this issue on the wrong repository. You should be using the new one instead! It's [here](https://github.com/MakeSchool-Tutorials/Makestagram-Swift-V2)

**Comment by rahb3rt** [comment]
@djh- tried that.. I think the new way to do is through `self.post?.image.value == nil` that loads the images after the second time refreshing the timeline screen. 

I included this function `dispatch_async(dispatch_get_main_queue())` before  the first `if` statement and that seems to fix that issue. Ill close this and thank you!
