### ISSUE TITLE
Link to project template is broken

### ISSUE THREAD

**Issue by ghost** [MakeSchool-Tutorials/Makestagram-Swift#5]
The link referenced in section 5 (Setting up the Xcode Project) is broken. It points here:
https://github.com/MakeSchool/Makestagram-Swift-Solution/archive/StarterProject.zip

I worked around this by creating a project according to the directions in the Z_NA-Setup-Custom-Xcode-Project directory, but presumably either the link or the surrounding material needs an update.

**Comment by Ben-G** [comment]
Fixed by Open-Sourcing the repo that this link was pointing to. Can you confirm and close? :)

**Comment by ghost** [comment]
Confirmed. Thanks!
